export const salesData = [
      {
        "id": 1,
        "region": "North America",
        "country": "USA",
        "city": "New York",
        "sales": 200,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-15",
        "manager": "John Doe",
        "latitude": 40.7128,
        "longitude": -74.0060
      },
      {
        "id": 2,
        "region": "Europe",
        "country": "Germany",
        "city": "Berlin",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-02-10",
        "manager": "Jane Smith",
        "latitude": 52.5200,
        "longitude": 13.4050
      },
      {
        "id": 3,
        "region": "Asia",
        "country": "India",
        "city": "Mumbai",
        "sales": 300,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-20",
        "manager": "Raj Patel",
        "latitude": 19.0760,
        "longitude": 72.8777
      },
      {
        "id": 4,
        "region": "Europe",
        "country": "UK",
        "city": "London",
        "sales": 250,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-04-05",
        "manager": "Alice Davis",
        "latitude": 51.5074,
        "longitude": -0.1278
      },
      {
        "id": 5,
        "region": "Asia",
        "country": "Japan",
        "city": "Tokyo",
        "sales": 180,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-05-12",
        "manager": "Yuki Tanaka",
        "latitude": 35.6895,
        "longitude": 139.6917
      },
      {
        "id": 6,
        "region": "South America",
        "country": "Brazil",
        "city": "São Paulo",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-06-01",
        "manager": "Carlos Silva",
        "latitude": -23.5505,
        "longitude": -46.6333
      },
      {
        "id": 7,
        "region": "North America",
        "country": "Canada",
        "city": "Toronto",
        "sales": 170,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-15",
        "manager": "Sarah Lee",
        "latitude": 43.65107,
        "longitude": -79.347015
      },
      {
        "id": 8,
        "region": "Europe",
        "country": "France",
        "city": "Paris",
        "sales": 400,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-08-09",
        "manager": "Pierre Martin",
        "latitude": 48.8566,
        "longitude": 2.3522
      },
      {
        "id": 9,
        "region": "Asia",
        "country": "China",
        "city": "Beijing",
        "sales": 270,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-09-20",
        "manager": "Li Wei",
        "latitude": 39.9042,
        "longitude": 116.4074
      },
      {
        "id": 10,
        "region": "South America",
        "country": "Argentina",
        "city": "Buenos Aires",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-11",
        "manager": "Laura Gomez",
        "latitude": -34.6037,
        "longitude": -58.3816
      },
      {
        "id": 11,
        "region": "North America",
        "country": "USA",
        "city": "Los Angeles",
        "sales": 210,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-18",
        "manager": "Michael Johnson",
        "latitude": 34.0522,
        "longitude": -118.2437
      },
      {
        "id": 12,
        "region": "Europe",
        "country": "Spain",
        "city": "Madrid",
        "sales": 185,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-02-05",
        "manager": "Luis Hernandez",
        "latitude": 40.4168,
        "longitude": -3.7038
      },
      {
        "id": 13,
        "region": "Asia",
        "country": "India",
        "city": "Delhi",
        "sales": 340,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-10",
        "manager": "Priya Sharma",
        "latitude": 28.6139,
        "longitude": 77.2090
      },
      {
        "id": 14,
        "region": "Europe",
        "country": "Italy",
        "city": "Rome",
        "sales": 270,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-04-21",
        "manager": "Giuseppe Romano",
        "latitude": 41.9028,
        "longitude": 12.4964
      },
      {
        "id": 15,
        "region": "South America",
        "country": "Chile",
        "city": "Santiago",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-05-01",
        "manager": "Juan Perez",
        "latitude": -33.4489,
        "longitude": -70.6693
      },
      {
        "id": 16,
        "region": "North America",
        "country": "Canada",
        "city": "Vancouver",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-06-03",
        "manager": "David Nguyen",
        "latitude": 49.2827,
        "longitude": -123.1207
      },
      {
        "id": 17,
        "region": "Europe",
        "country": "Germany",
        "city": "Munich",
        "sales": 250,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-12",
        "manager": "Heike Muller",
        "latitude": 48.1351,
        "longitude": 11.5820
      },
      {
        "id": 18,
        "region": "Asia",
        "country": "South Korea",
        "city": "Seoul",
        "sales": 210,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-08-19",
        "manager": "Jin Lee",
        "latitude": 37.5665,
        "longitude": 126.9780
      },
      {
        "id": 19,
        "region": "South America",
        "country": "Peru",
        "city": "Lima",
        "sales": 180,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-09-25",
        "manager": "Ana Delgado",
        "latitude": -12.0464,
        "longitude": -77.0428
      },
      {
        "id": 20,
        "region": "North America",
        "country": "USA",
        "city": "Chicago",
        "sales": 230,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-10-06",
        "manager": "Robert Williams",
        "latitude": 41.8781,
        "longitude": -87.6298
      },
      {
        "id": 21,
        "region": "North America",
        "country": "USA",
        "city": "San Francisco",
        "sales": 220,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-20",
        "manager": "Amy Johnson",
        "latitude": 37.7749,
        "longitude": -122.4194
      },
      {
        "id": 22,
        "region": "Europe",
        "country": "France",
        "city": "Lyon",
        "sales": 190,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-01-22",
        "manager": "Emilie Dubois",
        "latitude": 45.7640,
        "longitude": 4.8357
      },
      {
        "id": 23,
        "region": "Asia",
        "country": "China",
        "city": "Shanghai",
        "sales": 210,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-02-17",
        "manager": "Hua Zhang",
        "latitude": 31.2304,
        "longitude": 121.4737
      },
      {
        "id": 24,
        "region": "South America",
        "country": "Mexico",
        "city": "Mexico City",
        "sales": 250,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-03-01",
        "manager": "Luis Rios",
        "latitude": 19.4326,
        "longitude": -99.1332
      },
      {
        "id": 25,
        "region": "North America",
        "country": "USA",
        "city": "Seattle",
        "sales": 260,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-04-18",
        "manager": "Jessica Brown",
        "latitude": 47.6062,
        "longitude": -122.3321
      },
      {
        "id": 26,
        "region": "Europe",
        "country": "Italy",
        "city": "Milan",
        "sales": 300,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-05-03",
        "manager": "Francesco Rossi",
        "latitude": 45.4642,
        "longitude": 9.1900
      },
      {
        "id": 27,
        "region": "Asia",
        "country": "India",
        "city": "Bangalore",
        "sales": 150,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-06-14",
        "manager": "Vishal Kumar",
        "latitude": 12.9716,
        "longitude": 77.5946
      },
      {
        "id": 28,
        "region": "South America",
        "country": "Argentina",
        "city": "Cordoba",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-07-04",
        "manager": "Sofia Cruz",
        "latitude": -31.4201,
        "longitude": -64.1888
      },
      {
        "id": 29,
        "region": "North America",
        "country": "Canada",
        "city": "Montreal",
        "sales": 190,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-08-23",
        "manager": "Marc Lefevre",
        "latitude": 45.5017,
        "longitude": -73.5673
      },
      {
        "id": 30,
        "region": "Europe",
        "country": "Germany",
        "city": "Hamburg",
        "sales": 280,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-09-10",
        "manager": "Stefan Becker",
        "latitude": 53.5511,
        "longitude": 9.9937
      },
      {
        "id": 31,
        "region": "North America",
        "country": "USA",
        "city": "New York",
        "sales": 200,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-15",
        "manager": "John Doe",
        "latitude": 40.7128,
        "longitude": -74.0060
      },
      {
        "id": 32,
        "region": "Europe",
        "country": "Germany",
        "city": "Berlin",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-02-10",
        "manager": "Jane Smith",
        "latitude": 52.5200,
        "longitude": 13.4050
      },
      {
        "id": 33,
        "region": "Asia",
        "country": "India",
        "city": "Mumbai",
        "sales": 300,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-20",
        "manager": "Raj Patel",
        "latitude": 19.0760,
        "longitude": 72.8777
      },
      {
        "id": 34,
        "region": "Europe",
        "country": "UK",
        "city": "London",
        "sales": 250,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-04-05",
        "manager": "Alice Davis",
        "latitude": 51.5074,
        "longitude": -0.1278
      },
      {
        "id": 35,
        "region": "Asia",
        "country": "Japan",
        "city": "Tokyo",
        "sales": 180,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-05-12",
        "manager": "Yuki Tanaka",
        "latitude": 35.6895,
        "longitude": 139.6917
      },
      {
        "id": 36,
        "region": "South America",
        "country": "Brazil",
        "city": "São Paulo",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-06-01",
        "manager": "Carlos Silva",
        "latitude": -23.5505,
        "longitude": -46.6333
      },
      {
        "id": 37,
        "region": "North America",
        "country": "Canada",
        "city": "Toronto",
        "sales": 170,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-15",
        "manager": "Sarah Lee",
        "latitude": 43.65107,
        "longitude": -79.347015
      },
      {
        "id": 38,
        "region": "Europe",
        "country": "France",
        "city": "Paris",
        "sales": 400,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-08-09",
        "manager": "Pierre Martin",
        "latitude": 48.8566,
        "longitude": 2.3522
      },
      {
        "id": 39,
        "region": "Asia",
        "country": "China",
        "city": "Beijing",
        "sales": 270,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-09-20",
        "manager": "Li Wei",
        "latitude": 39.9042,
        "longitude": 116.4074
      },
      {
        "id": 40,
        "region": "South America",
        "country": "Argentina",
        "city": "Buenos Aires",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-11",
        "manager": "Laura Gomez",
        "latitude": -34.6037,
        "longitude": -58.3816
      },
      {
        "id": 41,
        "region": "North America",
        "country": "USA",
        "city": "Los Angeles",
        "sales": 210,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-18",
        "manager": "Michael Johnson",
        "latitude": 34.0522,
        "longitude": -118.2437
      },
      {
        "id": 42,
        "region": "Europe",
        "country": "Spain",
        "city": "Madrid",
        "sales": 185,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-02-05",
        "manager": "Luis Hernandez",
        "latitude": 40.4168,
        "longitude": -3.7038
      },
      {
        "id": 43,
        "region": "Asia",
        "country": "India",
        "city": "Delhi",
        "sales": 340,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-10",
        "manager": "Priya Sharma",
        "latitude": 28.6139,
        "longitude": 77.2090
      },
      {
        "id": 44,
        "region": "Europe",
        "country": "Italy",
        "city": "Rome",
        "sales": 270,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-04-21",
        "manager": "Giuseppe Romano",
        "latitude": 41.9028,
        "longitude": 12.4964
      },
      {
        "id": 45,
        "region": "South America",
        "country": "Chile",
        "city": "Santiago",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-05-01",
        "manager": "Juan Perez",
        "latitude": -33.4489,
        "longitude": -70.6693
      },
      {
        "id": 46,
        "region": "North America",
        "country": "Canada",
        "city": "Vancouver",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-06-03",
        "manager": "David Nguyen",
        "latitude": 49.2827,
        "longitude": -123.1207
      },
      {
        "id": 47,
        "region": "Europe",
        "country": "Germany",
        "city": "Munich",
        "sales": 250,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-12",
        "manager": "Heike Muller",
        "latitude": 48.1351,
        "longitude": 11.5820
      },
      {
        "id": 48,
        "region": "Asia",
        "country": "South Korea",
        "city": "Seoul",
        "sales": 210,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-08-19",
        "manager": "Jin Lee",
        "latitude": 37.5665,
        "longitude": 126.9780
      },
      {
        "id": 49,
        "region": "South America",
        "country": "Peru",
        "city": "Lima",
        "sales": 180,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-09-25",
        "manager": "Ana Delgado",
        "latitude": -12.0464,
        "longitude": -77.0428
      },
      {
        "id": 50,
        "region": "North America",
        "country": "USA",
        "city": "Chicago",
        "sales": 230,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-10-06",
        "manager": "Robert Williams",
        "latitude": 41.8781,
        "longitude": -87.6298
      },
      {
        "id": 51,
        "region": "North America",
        "country": "USA",
        "city": "San Francisco",
        "sales": 220,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-20",
        "manager": "Amy Johnson",
        "latitude": 37.7749,
        "longitude": -122.4194
      },
      {
        "id": 52,
        "region": "Europe",
        "country": "France",
        "city": "Lyon",
        "sales": 190,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-01-22",
        "manager": "Emilie Dubois",
        "latitude": 45.7640,
        "longitude": 4.8357
      },
      {
        "id": 53,
        "region": "Asia",
        "country": "China",
        "city": "Shanghai",
        "sales": 210,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-02-17",
        "manager": "Hua Zhang",
        "latitude": 31.2304,
        "longitude": 121.4737
      },
      {
        "id": 54,
        "region": "South America",
        "country": "Mexico",
        "city": "Mexico City",
        "sales": 250,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-03-01",
        "manager": "Luis Rios",
        "latitude": 19.4326,
        "longitude": -99.1332
      },
      {
        "id": 55,
        "region": "North America",
        "country": "USA",
        "city": "Seattle",
        "sales": 260,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-04-18",
        "manager": "Jessica Brown",
        "latitude": 47.6062,
        "longitude": -122.3321
      },
      {
        "id": 56,
        "region": "Europe",
        "country": "Italy",
        "city": "Milan",
        "sales": 300,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-05-03",
        "manager": "Francesco Rossi",
        "latitude": 45.4642,
        "longitude": 9.1900
      },
      {
        "id": 57,
        "region": "Asia",
        "country": "India",
        "city": "Bangalore",
        "sales": 150,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-06-14",
        "manager": "Vishal Kumar",
        "latitude": 12.9716,
        "longitude": 77.5946
      },
      {
        "id": 58,
        "region": "South America",
        "country": "Argentina",
        "city": "Cordoba",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-07-04",
        "manager": "Sofia Cruz",
        "latitude": -31.4201,
        "longitude": -64.1888
      },
      {
        "id": 59,
        "region": "North America",
        "country": "Canada",
        "city": "Montreal",
        "sales": 190,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-08-23",
        "manager": "Marc Lefevre",
        "latitude": 45.5017,
        "longitude": -73.5673
      },
      {
        "id": 60,
        "region": "Europe",
        "country": "Germany",
        "city": "Hamburg",
        "sales": 280,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-09-10",
        "manager": "Stefan Becker",
        "latitude": 53.5511,
        "longitude": 9.9937
      },
      {
        "id": 61,
        "region": "North America",
        "country": "USA",
        "city": "New York",
        "sales": 200,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-15",
        "manager": "John Doe",
        "latitude": 40.7128,
        "longitude": -74.0060
      },
      {
        "id": 62,
        "region": "Europe",
        "country": "Germany",
        "city": "Berlin",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-02-10",
        "manager": "Jane Smith",
        "latitude": 52.5200,
        "longitude": 13.4050
      },
      {
        "id": 63,
        "region": "Asia",
        "country": "India",
        "city": "Mumbai",
        "sales": 300,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-20",
        "manager": "Raj Patel",
        "latitude": 19.0760,
        "longitude": 72.8777
      },
      {
        "id": 64,
        "region": "Europe",
        "country": "UK",
        "city": "London",
        "sales": 250,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-04-05",
        "manager": "Alice Davis",
        "latitude": 51.5074,
        "longitude": -0.1278
      },
      {
        "id": 65,
        "region": "Asia",
        "country": "Japan",
        "city": "Tokyo",
        "sales": 180,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-05-12",
        "manager": "Yuki Tanaka",
        "latitude": 35.6895,
        "longitude": 139.6917
      },
      {
        "id": 66,
        "region": "South America",
        "country": "Brazil",
        "city": "São Paulo",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-06-01",
        "manager": "Carlos Silva",
        "latitude": -23.5505,
        "longitude": -46.6333
      },
      {
        "id": 67,
        "region": "North America",
        "country": "Canada",
        "city": "Toronto",
        "sales": 170,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-15",
        "manager": "Sarah Lee",
        "latitude": 43.65107,
        "longitude": -79.347015
      },
      {
        "id": 68,
        "region": "Europe",
        "country": "France",
        "city": "Paris",
        "sales": 400,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-08-09",
        "manager": "Pierre Martin",
        "latitude": 48.8566,
        "longitude": 2.3522
      },
      {
        "id": 69,
        "region": "Asia",
        "country": "China",
        "city": "Beijing",
        "sales": 270,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-09-20",
        "manager": "Li Wei",
        "latitude": 39.9042,
        "longitude": 116.4074
      },
      {
        "id": 70,
        "region": "South America",
        "country": "Argentina",
        "city": "Buenos Aires",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-11",
        "manager": "Laura Gomez",
        "latitude": -34.6037,
        "longitude": -58.3816
      },
      {
        "id": 71,
        "region": "North America",
        "country": "USA",
        "city": "Los Angeles",
        "sales": 210,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-18",
        "manager": "Michael Johnson",
        "latitude": 34.0522,
        "longitude": -118.2437
      },
      {
        "id": 72,
        "region": "Europe",
        "country": "Spain",
        "city": "Madrid",
        "sales": 185,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-02-05",
        "manager": "Luis Hernandez",
        "latitude": 40.4168,
        "longitude": -3.7038
      },
      {
        "id": 73,
        "region": "Asia",
        "country": "India",
        "city": "Delhi",
        "sales": 340,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-10",
        "manager": "Priya Sharma",
        "latitude": 28.6139,
        "longitude": 77.2090
      },
      {
        "id": 74,
        "region": "Europe",
        "country": "Italy",
        "city": "Rome",
        "sales": 270,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-04-21",
        "manager": "Giuseppe Romano",
        "latitude": 41.9028,
        "longitude": 12.4964
      },
      {
        "id": 75,
        "region": "South America",
        "country": "Chile",
        "city": "Santiago",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-05-01",
        "manager": "Juan Perez",
        "latitude": -33.4489,
        "longitude": -70.6693
      },
      {
        "id": 76,
        "region": "North America",
        "country": "Canada",
        "city": "Vancouver",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-06-03",
        "manager": "David Nguyen",
        "latitude": 49.2827,
        "longitude": -123.1207
      },
      {
        "id": 77,
        "region": "Europe",
        "country": "Germany",
        "city": "Munich",
        "sales": 250,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-12",
        "manager": "Heike Muller",
        "latitude": 48.1351,
        "longitude": 11.5820
      },
      {
        "id": 78,
        "region": "Asia",
        "country": "South Korea",
        "city": "Seoul",
        "sales": 210,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-08-19",
        "manager": "Jin Lee",
        "latitude": 37.5665,
        "longitude": 126.9780
      },
      {
        "id": 79,
        "region": "South America",
        "country": "Peru",
        "city": "Lima",
        "sales": 180,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-09-25",
        "manager": "Ana Delgado",
        "latitude": -12.0464,
        "longitude": -77.0428
      },
      {
        "id": 80,
        "region": "North America",
        "country": "USA",
        "city": "Chicago",
        "sales": 230,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-10-06",
        "manager": "Robert Williams",
        "latitude": 41.8781,
        "longitude": -87.6298
      },
      {
        "id": 81,
        "region": "North America",
        "country": "USA",
        "city": "San Francisco",
        "sales": 220,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-20",
        "manager": "Amy Johnson",
        "latitude": 37.7749,
        "longitude": -122.4194
      },
      {
        "id": 82,
        "region": "Europe",
        "country": "France",
        "city": "Lyon",
        "sales": 190,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-01-22",
        "manager": "Emilie Dubois",
        "latitude": 45.7640,
        "longitude": 4.8357
      },
      {
        "id": 83,
        "region": "Asia",
        "country": "China",
        "city": "Shanghai",
        "sales": 210,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-02-17",
        "manager": "Hua Zhang",
        "latitude": 31.2304,
        "longitude": 121.4737
      },
      {
        "id": 84,
        "region": "South America",
        "country": "Mexico",
        "city": "Mexico City",
        "sales": 250,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-03-01",
        "manager": "Luis Rios",
        "latitude": 19.4326,
        "longitude": -99.1332
      },
      {
        "id": 85,
        "region": "North America",
        "country": "USA",
        "city": "Seattle",
        "sales": 260,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-04-18",
        "manager": "Jessica Brown",
        "latitude": 47.6062,
        "longitude": -122.3321
      },
      {
        "id": 86,
        "region": "Europe",
        "country": "Italy",
        "city": "Milan",
        "sales": 300,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-05-03",
        "manager": "Francesco Rossi",
        "latitude": 45.4642,
        "longitude": 9.1900
      },
      {
        "id": 87,
        "region": "Asia",
        "country": "India",
        "city": "Bangalore",
        "sales": 150,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-06-14",
        "manager": "Vishal Kumar",
        "latitude": 12.9716,
        "longitude": 77.5946
      },
      {
        "id": 88,
        "region": "South America",
        "country": "Argentina",
        "city": "Cordoba",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-07-04",
        "manager": "Sofia Cruz",
        "latitude": -31.4201,
        "longitude": -64.1888
      },
      {
        "id": 89,
        "region": "North America",
        "country": "Canada",
        "city": "Montreal",
        "sales": 190,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-08-23",
        "manager": "Marc Lefevre",
        "latitude": 45.5017,
        "longitude": -73.5673
      },
      {
        "id": 90,
        "region": "Europe",
        "country": "Germany",
        "city": "Hamburg",
        "sales": 280,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-09-10",
        "manager": "Stefan Becker",
        "latitude": 53.5511,
        "longitude": 9.9937
      },
      {
        "id": 91,
        "region": "North America",
        "country": "USA",
        "city": "New York",
        "sales": 200,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-15",
        "manager": "John Doe",
        "latitude": 40.7128,
        "longitude": -74.0060
      },
      {
        "id": 92,
        "region": "Europe",
        "country": "Germany",
        "city": "Berlin",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-02-10",
        "manager": "Jane Smith",
        "latitude": 52.5200,
        "longitude": 13.4050
      },
      {
        "id": 93,
        "region": "Asia",
        "country": "India",
        "city": "Mumbai",
        "sales": 300,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-20",
        "manager": "Raj Patel",
        "latitude": 19.0760,
        "longitude": 72.8777
      },
      {
        "id": 94,
        "region": "Europe",
        "country": "UK",
        "city": "London",
        "sales": 250,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-04-05",
        "manager": "Alice Davis",
        "latitude": 51.5074,
        "longitude": -0.1278
      },
      {
        "id": 95,
        "region": "Asia",
        "country": "Japan",
        "city": "Tokyo",
        "sales": 180,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-05-12",
        "manager": "Yuki Tanaka",
        "latitude": 35.6895,
        "longitude": 139.6917
      },
      {
        "id": 96,
        "region": "South America",
        "country": "Brazil",
        "city": "São Paulo",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-06-01",
        "manager": "Carlos Silva",
        "latitude": -23.5505,
        "longitude": -46.6333
      },
      {
        "id": 97,
        "region": "North America",
        "country": "Canada",
        "city": "Toronto",
        "sales": 170,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-15",
        "manager": "Sarah Lee",
        "latitude": 43.65107,
        "longitude": -79.347015
      },
      {
        "id": 98,
        "region": "Europe",
        "country": "France",
        "city": "Paris",
        "sales": 400,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-08-09",
        "manager": "Pierre Martin",
        "latitude": 48.8566,
        "longitude": 2.3522
      },
      {
        "id": 99,
        "region": "Asia",
        "country": "China",
        "city": "Beijing",
        "sales": 270,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-09-20",
        "manager": "Li Wei",
        "latitude": 39.9042,
        "longitude": 116.4074
      },
      {
        "id": 100,
        "region": "South America",
        "country": "Argentina",
        "city": "Buenos Aires",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-11",
        "manager": "Laura Gomez",
        "latitude": -34.6037,
        "longitude": -58.3816
      },
      {
        "id": 101,
        "region": "North America",
        "country": "USA",
        "city": "Los Angeles",
        "sales": 210,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-18",
        "manager": "Michael Johnson",
        "latitude": 34.0522,
        "longitude": -118.2437
      },
      {
        "id": 102,
        "region": "Europe",
        "country": "Spain",
        "city": "Madrid",
        "sales": 185,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-02-05",
        "manager": "Luis Hernandez",
        "latitude": 40.4168,
        "longitude": -3.7038
      },
      {
        "id": 103,
        "region": "Asia",
        "country": "India",
        "city": "Delhi",
        "sales": 340,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-10",
        "manager": "Priya Sharma",
        "latitude": 28.6139,
        "longitude": 77.2090
      },
      {
        "id": 104,
        "region": "Europe",
        "country": "Italy",
        "city": "Rome",
        "sales": 270,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-04-21",
        "manager": "Giuseppe Romano",
        "latitude": 41.9028,
        "longitude": 12.4964
      },
      {
        "id": 105,
        "region": "South America",
        "country": "Chile",
        "city": "Santiago",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-05-01",
        "manager": "Juan Perez",
        "latitude": -33.4489,
        "longitude": -70.6693
      },
      {
        "id": 106,
        "region": "North America",
        "country": "Canada",
        "city": "Vancouver",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-06-03",
        "manager": "David Nguyen",
        "latitude": 49.2827,
        "longitude": -123.1207
      },
      {
        "id": 107,
        "region": "Europe",
        "country": "Germany",
        "city": "Munich",
        "sales": 250,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-12",
        "manager": "Heike Muller",
        "latitude": 48.1351,
        "longitude": 11.5820
      },
      {
        "id": 108,
        "region": "Asia",
        "country": "South Korea",
        "city": "Seoul",
        "sales": 210,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-08-19",
        "manager": "Jin Lee",
        "latitude": 37.5665,
        "longitude": 126.9780
      },
      {
        "id": 109,
        "region": "South America",
        "country": "Peru",
        "city": "Lima",
        "sales": 180,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-09-25",
        "manager": "Ana Delgado",
        "latitude": -12.0464,
        "longitude": -77.0428
      },
      {
        "id": 120,
        "region": "North America",
        "country": "USA",
        "city": "Chicago",
        "sales": 230,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-10-06",
        "manager": "Robert Williams",
        "latitude": 41.8781,
        "longitude": -87.6298
      },
      {
        "id": 121,
        "region": "North America",
        "country": "USA",
        "city": "San Francisco",
        "sales": 220,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-20",
        "manager": "Amy Johnson",
        "latitude": 37.7749,
        "longitude": -122.4194
      },
      {
        "id": 122,
        "region": "Europe",
        "country": "France",
        "city": "Lyon",
        "sales": 190,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-01-22",
        "manager": "Emilie Dubois",
        "latitude": 45.7640,
        "longitude": 4.8357
      },
      {
        "id": 123,
        "region": "Asia",
        "country": "China",
        "city": "Shanghai",
        "sales": 210,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-02-17",
        "manager": "Hua Zhang",
        "latitude": 31.2304,
        "longitude": 121.4737
      },
      {
        "id": 124,
        "region": "South America",
        "country": "Mexico",
        "city": "Mexico City",
        "sales": 250,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-03-01",
        "manager": "Luis Rios",
        "latitude": 19.4326,
        "longitude": -99.1332
      },
      {
        "id": 125,
        "region": "North America",
        "country": "USA",
        "city": "Seattle",
        "sales": 260,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-04-18",
        "manager": "Jessica Brown",
        "latitude": 47.6062,
        "longitude": -122.3321
      },
      {
        "id": 126,
        "region": "Europe",
        "country": "Italy",
        "city": "Milan",
        "sales": 300,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-05-03",
        "manager": "Francesco Rossi",
        "latitude": 45.4642,
        "longitude": 9.1900
      },
      {
        "id": 127,
        "region": "Asia",
        "country": "India",
        "city": "Bangalore",
        "sales": 150,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-06-14",
        "manager": "Vishal Kumar",
        "latitude": 12.9716,
        "longitude": 77.5946
      },
      {
        "id": 128,
        "region": "South America",
        "country": "Argentina",
        "city": "Cordoba",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-07-04",
        "manager": "Sofia Cruz",
        "latitude": -31.4201,
        "longitude": -64.1888
      },
      {
        "id": 129,
        "region": "North America",
        "country": "Canada",
        "city": "Montreal",
        "sales": 190,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-08-23",
        "manager": "Marc Lefevre",
        "latitude": 45.5017,
        "longitude": -73.5673
      },
      {
        "id": 130,
        "region": "Europe",
        "country": "Germany",
        "city": "Hamburg",
        "sales": 280,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-09-10",
        "manager": "Stefan Becker",
        "latitude": 53.5511,
        "longitude": 9.9937
      },
      {
        "id": 131,
        "region": "North America",
        "country": "USA",
        "city": "New York",
        "sales": 200,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-15",
        "manager": "John Doe",
        "latitude": 40.7128,
        "longitude": -74.0060
      },
      {
        "id": 132,
        "region": "Europe",
        "country": "Germany",
        "city": "Berlin",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-02-10",
        "manager": "Jane Smith",
        "latitude": 52.5200,
        "longitude": 13.4050
      },
      {
        "id": 133,
        "region": "Asia",
        "country": "India",
        "city": "Mumbai",
        "sales": 300,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-20",
        "manager": "Raj Patel",
        "latitude": 19.0760,
        "longitude": 72.8777
      },
      {
        "id": 134,
        "region": "Europe",
        "country": "UK",
        "city": "London",
        "sales": 250,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-04-05",
        "manager": "Alice Davis",
        "latitude": 51.5074,
        "longitude": -0.1278
      },
      {
        "id": 135,
        "region": "Asia",
        "country": "Japan",
        "city": "Tokyo",
        "sales": 180,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-05-12",
        "manager": "Yuki Tanaka",
        "latitude": 35.6895,
        "longitude": 139.6917
      },
      {
        "id": 136,
        "region": "South America",
        "country": "Brazil",
        "city": "São Paulo",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-06-01",
        "manager": "Carlos Silva",
        "latitude": -23.5505,
        "longitude": -46.6333
      },
      {
        "id": 137,
        "region": "North America",
        "country": "Canada",
        "city": "Toronto",
        "sales": 170,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-15",
        "manager": "Sarah Lee",
        "latitude": 43.65107,
        "longitude": -79.347015
      },
      {
        "id": 138,
        "region": "Europe",
        "country": "France",
        "city": "Paris",
        "sales": 400,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-08-09",
        "manager": "Pierre Martin",
        "latitude": 48.8566,
        "longitude": 2.3522
      },
      {
        "id": 139,
        "region": "Asia",
        "country": "China",
        "city": "Beijing",
        "sales": 270,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-09-20",
        "manager": "Li Wei",
        "latitude": 39.9042,
        "longitude": 116.4074
      },
      {
        "id": 140,
        "region": "South America",
        "country": "Argentina",
        "city": "Buenos Aires",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-11",
        "manager": "Laura Gomez",
        "latitude": -34.6037,
        "longitude": -58.3816
      },
      {
        "id": 141,
        "region": "North America",
        "country": "USA",
        "city": "Los Angeles",
        "sales": 210,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-18",
        "manager": "Michael Johnson",
        "latitude": 34.0522,
        "longitude": -118.2437
      },
      {
        "id": 142,
        "region": "Europe",
        "country": "Spain",
        "city": "Madrid",
        "sales": 185,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-02-05",
        "manager": "Luis Hernandez",
        "latitude": 40.4168,
        "longitude": -3.7038
      },
      {
        "id": 143,
        "region": "Asia",
        "country": "India",
        "city": "Delhi",
        "sales": 340,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-10",
        "manager": "Priya Sharma",
        "latitude": 28.6139,
        "longitude": 77.2090
      },
      {
        "id": 144,
        "region": "Europe",
        "country": "Italy",
        "city": "Rome",
        "sales": 270,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-04-21",
        "manager": "Giuseppe Romano",
        "latitude": 41.9028,
        "longitude": 12.4964
      },
      {
        "id": 145,
        "region": "South America",
        "country": "Chile",
        "city": "Santiago",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-05-01",
        "manager": "Juan Perez",
        "latitude": -33.4489,
        "longitude": -70.6693
      },
      {
        "id": 146,
        "region": "North America",
        "country": "Canada",
        "city": "Vancouver",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-06-03",
        "manager": "David Nguyen",
        "latitude": 49.2827,
        "longitude": -123.1207
      },
      {
        "id": 147,
        "region": "Europe",
        "country": "Germany",
        "city": "Munich",
        "sales": 250,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-12",
        "manager": "Heike Muller",
        "latitude": 48.1351,
        "longitude": 11.5820
      },
      {
        "id": 148,
        "region": "Asia",
        "country": "South Korea",
        "city": "Seoul",
        "sales": 210,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-08-19",
        "manager": "Jin Lee",
        "latitude": 37.5665,
        "longitude": 126.9780
      },
      {
        "id": 149,
        "region": "South America",
        "country": "Peru",
        "city": "Lima",
        "sales": 180,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-09-25",
        "manager": "Ana Delgado",
        "latitude": -12.0464,
        "longitude": -77.0428
      },
      {
        "id": 150,
        "region": "North America",
        "country": "USA",
        "city": "Chicago",
        "sales": 230,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-10-06",
        "manager": "Robert Williams",
        "latitude": 41.8781,
        "longitude": -87.6298
      },
      {
        "id": 151,
        "region": "North America",
        "country": "USA",
        "city": "San Francisco",
        "sales": 220,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-20",
        "manager": "Amy Johnson",
        "latitude": 37.7749,
        "longitude": -122.4194
      },
      {
        "id": 152,
        "region": "Europe",
        "country": "France",
        "city": "Lyon",
        "sales": 190,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-01-22",
        "manager": "Emilie Dubois",
        "latitude": 45.7640,
        "longitude": 4.8357
      },
      {
        "id": 153,
        "region": "Asia",
        "country": "China",
        "city": "Shanghai",
        "sales": 210,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-02-17",
        "manager": "Hua Zhang",
        "latitude": 31.2304,
        "longitude": 121.4737
      },
      {
        "id": 154,
        "region": "South America",
        "country": "Mexico",
        "city": "Mexico City",
        "sales": 250,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-03-01",
        "manager": "Luis Rios",
        "latitude": 19.4326,
        "longitude": -99.1332
      },
      {
        "id": 155,
        "region": "North America",
        "country": "USA",
        "city": "Seattle",
        "sales": 260,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-04-18",
        "manager": "Jessica Brown",
        "latitude": 47.6062,
        "longitude": -122.3321
      },
      {
        "id": 156,
        "region": "Europe",
        "country": "Italy",
        "city": "Milan",
        "sales": 300,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-05-03",
        "manager": "Francesco Rossi",
        "latitude": 45.4642,
        "longitude": 9.1900
      },
      {
        "id": 157,
        "region": "Asia",
        "country": "India",
        "city": "Bangalore",
        "sales": 150,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-06-14",
        "manager": "Vishal Kumar",
        "latitude": 12.9716,
        "longitude": 77.5946
      },
      {
        "id": 158,
        "region": "South America",
        "country": "Argentina",
        "city": "Cordoba",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-07-04",
        "manager": "Sofia Cruz",
        "latitude": -31.4201,
        "longitude": -64.1888
      },
      {
        "id": 159,
        "region": "North America",
        "country": "Canada",
        "city": "Montreal",
        "sales": 190,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-08-23",
        "manager": "Marc Lefevre",
        "latitude": 45.5017,
        "longitude": -73.5673
      },
      {
        "id": 160,
        "region": "Europe",
        "country": "Germany",
        "city": "Hamburg",
        "sales": 280,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-09-10",
        "manager": "Stefan Becker",
        "latitude": 53.5511,
        "longitude": 9.9937
      },
      {
        "id": 161,
        "region": "North America",
        "country": "USA",
        "city": "New York",
        "sales": 200,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-15",
        "manager": "John Doe",
        "latitude": 40.7128,
        "longitude": -74.0060
      },
      {
        "id": 162,
        "region": "Europe",
        "country": "Germany",
        "city": "Berlin",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-02-10",
        "manager": "Jane Smith",
        "latitude": 52.5200,
        "longitude": 13.4050
      },
      {
        "id": 163,
        "region": "Asia",
        "country": "India",
        "city": "Mumbai",
        "sales": 300,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-20",
        "manager": "Raj Patel",
        "latitude": 19.0760,
        "longitude": 72.8777
      },
      {
        "id": 164,
        "region": "Europe",
        "country": "UK",
        "city": "London",
        "sales": 250,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-04-05",
        "manager": "Alice Davis",
        "latitude": 51.5074,
        "longitude": -0.1278
      },
      {
        "id": 165,
        "region": "Asia",
        "country": "Japan",
        "city": "Tokyo",
        "sales": 180,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-05-12",
        "manager": "Yuki Tanaka",
        "latitude": 35.6895,
        "longitude": 139.6917
      },
      {
        "id": 166,
        "region": "South America",
        "country": "Brazil",
        "city": "São Paulo",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-06-01",
        "manager": "Carlos Silva",
        "latitude": -23.5505,
        "longitude": -46.6333
      },
      {
        "id": 167,
        "region": "North America",
        "country": "Canada",
        "city": "Toronto",
        "sales": 170,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-15",
        "manager": "Sarah Lee",
        "latitude": 43.65107,
        "longitude": -79.347015
      },
      {
        "id": 168,
        "region": "Europe",
        "country": "France",
        "city": "Paris",
        "sales": 400,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-08-09",
        "manager": "Pierre Martin",
        "latitude": 48.8566,
        "longitude": 2.3522
      },
      {
        "id": 169,
        "region": "Asia",
        "country": "China",
        "city": "Beijing",
        "sales": 270,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-09-20",
        "manager": "Li Wei",
        "latitude": 39.9042,
        "longitude": 116.4074
      },
      {
        "id": 170,
        "region": "South America",
        "country": "Argentina",
        "city": "Buenos Aires",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-11",
        "manager": "Laura Gomez",
        "latitude": -34.6037,
        "longitude": -58.3816
      },
      {
        "id": 171,
        "region": "North America",
        "country": "USA",
        "city": "Los Angeles",
        "sales": 210,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-18",
        "manager": "Michael Johnson",
        "latitude": 34.0522,
        "longitude": -118.2437
      },
      {
        "id": 172,
        "region": "Europe",
        "country": "Spain",
        "city": "Madrid",
        "sales": 185,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-02-05",
        "manager": "Luis Hernandez",
        "latitude": 40.4168,
        "longitude": -3.7038
      },
      {
        "id": 173,
        "region": "Asia",
        "country": "India",
        "city": "Delhi",
        "sales": 340,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-10",
        "manager": "Priya Sharma",
        "latitude": 28.6139,
        "longitude": 77.2090
      },
      {
        "id": 174,
        "region": "Europe",
        "country": "Italy",
        "city": "Rome",
        "sales": 270,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-04-21",
        "manager": "Giuseppe Romano",
        "latitude": 41.9028,
        "longitude": 12.4964
      },
      {
        "id": 175,
        "region": "South America",
        "country": "Chile",
        "city": "Santiago",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-05-01",
        "manager": "Juan Perez",
        "latitude": -33.4489,
        "longitude": -70.6693
      },
      {
        "id": 176,
        "region": "North America",
        "country": "Canada",
        "city": "Vancouver",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-06-03",
        "manager": "David Nguyen",
        "latitude": 49.2827,
        "longitude": -123.1207
      },
      {
        "id": 177,
        "region": "Europe",
        "country": "Germany",
        "city": "Munich",
        "sales": 250,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-12",
        "manager": "Heike Muller",
        "latitude": 48.1351,
        "longitude": 11.5820
      },
      {
        "id": 178,
        "region": "Asia",
        "country": "South Korea",
        "city": "Seoul",
        "sales": 210,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-08-19",
        "manager": "Jin Lee",
        "latitude": 37.5665,
        "longitude": 126.9780
      },
      {
        "id": 179,
        "region": "South America",
        "country": "Peru",
        "city": "Lima",
        "sales": 180,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-09-25",
        "manager": "Ana Delgado",
        "latitude": -12.0464,
        "longitude": -77.0428
      },
      {
        "id": 180,
        "region": "North America",
        "country": "USA",
        "city": "Chicago",
        "sales": 230,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-10-06",
        "manager": "Robert Williams",
        "latitude": 41.8781,
        "longitude": -87.6298
      },
      {
        "id": 181,
        "region": "North America",
        "country": "USA",
        "city": "San Francisco",
        "sales": 220,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-20",
        "manager": "Amy Johnson",
        "latitude": 37.7749,
        "longitude": -122.4194
      },
      {
        "id": 182,
        "region": "Europe",
        "country": "France",
        "city": "Lyon",
        "sales": 190,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-01-22",
        "manager": "Emilie Dubois",
        "latitude": 45.7640,
        "longitude": 4.8357
      },
      {
        "id": 183,
        "region": "Asia",
        "country": "China",
        "city": "Shanghai",
        "sales": 210,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-02-17",
        "manager": "Hua Zhang",
        "latitude": 31.2304,
        "longitude": 121.4737
      },
      {
        "id": 184,
        "region": "South America",
        "country": "Mexico",
        "city": "Mexico City",
        "sales": 250,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-03-01",
        "manager": "Luis Rios",
        "latitude": 19.4326,
        "longitude": -99.1332
      },
      {
        "id": 185,
        "region": "North America",
        "country": "USA",
        "city": "Seattle",
        "sales": 260,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-04-18",
        "manager": "Jessica Brown",
        "latitude": 47.6062,
        "longitude": -122.3321
      },
      {
        "id": 186,
        "region": "Europe",
        "country": "Italy",
        "city": "Milan",
        "sales": 300,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-05-03",
        "manager": "Francesco Rossi",
        "latitude": 45.4642,
        "longitude": 9.1900
      },
      {
        "id": 187,
        "region": "Asia",
        "country": "India",
        "city": "Bangalore",
        "sales": 150,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-06-14",
        "manager": "Vishal Kumar",
        "latitude": 12.9716,
        "longitude": 77.5946
      },
      {
        "id": 188,
        "region": "South America",
        "country": "Argentina",
        "city": "Cordoba",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-07-04",
        "manager": "Sofia Cruz",
        "latitude": -31.4201,
        "longitude": -64.1888
      },
      {
        "id": 189,
        "region": "North America",
        "country": "Canada",
        "city": "Montreal",
        "sales": 190,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-08-23",
        "manager": "Marc Lefevre",
        "latitude": 45.5017,
        "longitude": -73.5673
      },
      {
        "id": 190,
        "region": "Europe",
        "country": "Germany",
        "city": "Hamburg",
        "sales": 280,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-09-10",
        "manager": "Stefan Becker",
        "latitude": 53.5511,
        "longitude": 9.9937
      },
      {
        "id": 191,
        "region": "North America",
        "country": "USA",
        "city": "New York",
        "sales": 200,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-15",
        "manager": "John Doe",
        "latitude": 40.7128,
        "longitude": -74.0060
      },
      {
        "id": 192,
        "region": "Europe",
        "country": "Germany",
        "city": "Berlin",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-02-10",
        "manager": "Jane Smith",
        "latitude": 52.5200,
        "longitude": 13.4050
      },
      {
        "id": 193,
        "region": "Asia",
        "country": "India",
        "city": "Mumbai",
        "sales": 300,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-20",
        "manager": "Raj Patel",
        "latitude": 19.0760,
        "longitude": 72.8777
      },
      {
        "id": 194,
        "region": "Europe",
        "country": "UK",
        "city": "London",
        "sales": 250,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-04-05",
        "manager": "Alice Davis",
        "latitude": 51.5074,
        "longitude": -0.1278
      },
      {
        "id": 195,
        "region": "Asia",
        "country": "Japan",
        "city": "Tokyo",
        "sales": 180,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-05-12",
        "manager": "Yuki Tanaka",
        "latitude": 35.6895,
        "longitude": 139.6917
      },
      {
        "id": 196,
        "region": "South America",
        "country": "Brazil",
        "city": "São Paulo",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-06-01",
        "manager": "Carlos Silva",
        "latitude": -23.5505,
        "longitude": -46.6333
      },
      {
        "id": 197,
        "region": "North America",
        "country": "Canada",
        "city": "Toronto",
        "sales": 170,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-15",
        "manager": "Sarah Lee",
        "latitude": 43.65107,
        "longitude": -79.347015
      },
      {
        "id": 198,
        "region": "Europe",
        "country": "France",
        "city": "Paris",
        "sales": 400,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-08-09",
        "manager": "Pierre Martin",
        "latitude": 48.8566,
        "longitude": 2.3522
      },
      {
        "id": 199,
        "region": "Asia",
        "country": "China",
        "city": "Beijing",
        "sales": 270,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-09-20",
        "manager": "Li Wei",
        "latitude": 39.9042,
        "longitude": 116.4074
      },
      {
        "id": 200,
        "region": "South America",
        "country": "Argentina",
        "city": "Buenos Aires",
        "sales": 150,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-11",
        "manager": "Laura Gomez",
        "latitude": -34.6037,
        "longitude": -58.3816
      },
      {
        "id": 201,
        "region": "North America",
        "country": "USA",
        "city": "Los Angeles",
        "sales": 210,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-01-18",
        "manager": "Michael Johnson",
        "latitude": 34.0522,
        "longitude": -118.2437
      },
      {
        "id": 202,
        "region": "Europe",
        "country": "Spain",
        "city": "Madrid",
        "sales": 185,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-02-05",
        "manager": "Luis Hernandez",
        "latitude": 40.4168,
        "longitude": -3.7038
      },
      {
        "id": 203,
        "region": "Asia",
        "country": "India",
        "city": "Delhi",
        "sales": 340,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-03-10",
        "manager": "Priya Sharma",
        "latitude": 28.6139,
        "longitude": 77.2090
      },
      {
        "id": 204,
        "region": "Europe",
        "country": "Italy",
        "city": "Rome",
        "sales": 270,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-04-21",
        "manager": "Giuseppe Romano",
        "latitude": 41.9028,
        "longitude": 12.4964
      },
      {
        "id": 205,
        "region": "South America",
        "country": "Chile",
        "city": "Santiago",
        "sales": 220,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-05-01",
        "manager": "Juan Perez",
        "latitude": -33.4489,
        "longitude": -70.6693
      },
      {
        "id": 206,
        "region": "North America",
        "country": "Canada",
        "city": "Vancouver",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-06-03",
        "manager": "David Nguyen",
        "latitude": 49.2827,
        "longitude": -123.1207
      },
      {
        "id": 207,
        "region": "Europe",
        "country": "Germany",
        "city": "Munich",
        "sales": 250,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-07-12",
        "manager": "Heike Muller",
        "latitude": 48.1351,
        "longitude": 11.5820
      },
      {
        "id": 208,
        "region": "Asia",
        "country": "South Korea",
        "city": "Seoul",
        "sales": 210,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-08-19",
        "manager": "Jin Lee",
        "latitude": 37.5665,
        "longitude": 126.9780
      },
      {
        "id": 209,
        "region": "South America",
        "country": "Peru",
        "city": "Lima",
        "sales": 180,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-09-25",
        "manager": "Ana Delgado",
        "latitude": -12.0464,
        "longitude": -77.0428
      },
      {
        "id": 210,
        "region": "North America",
        "country": "USA",
        "city": "Chicago",
        "sales": 230,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-10-06",
        "manager": "Robert Williams",
        "latitude": 41.8781,
        "longitude": -87.6298
      },
      {
        "id": 211,
        "region": "North America",
        "country": "USA",
        "city": "San Francisco",
        "sales": 220,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-10-20",
        "manager": "Amy Johnson",
        "latitude": 37.7749,
        "longitude": -122.4194
      },
      {
        "id": 212,
        "region": "Europe",
        "country": "France",
        "city": "Lyon",
        "sales": 190,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-01-22",
        "manager": "Emilie Dubois",
        "latitude": 45.7640,
        "longitude": 4.8357
      },
      {
        "id": 213,
        "region": "Asia",
        "country": "China",
        "city": "Shanghai",
        "sales": 210,
        "product": "Camera",
        "category": "Electronics",
        "date": "2024-02-17",
        "manager": "Hua Zhang",
        "latitude": 31.2304,
        "longitude": 121.4737
      },
      {
        "id": 214,
        "region": "South America",
        "country": "Mexico",
        "city": "Mexico City",
        "sales": 250,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-03-01",
        "manager": "Luis Rios",
        "latitude": 19.4326,
        "longitude": -99.1332
      },
      {
        "id": 215,
        "region": "North America",
        "country": "USA",
        "city": "Seattle",
        "sales": 260,
        "product": "Laptop",
        "category": "Electronics",
        "date": "2024-04-18",
        "manager": "Jessica Brown",
        "latitude": 47.6062,
        "longitude": -122.3321
      },
      {
        "id": 216,
        "region": "Europe",
        "country": "Italy",
        "city": "Milan",
        "sales": 300,
        "product": "Smartphone",
        "category": "Electronics",
        "date": "2024-05-03",
        "manager": "Francesco Rossi",
        "latitude": 45.4642,
        "longitude": 9.1900
      },
      {
        "id": 217,
        "region": "Asia",
        "country": "India",
        "city": "Bangalore",
        "sales": 150,
        "product": "Tablet",
        "category": "Electronics",
        "date": "2024-06-14",
        "manager": "Vishal Kumar",
        "latitude": 12.9716,
        "longitude": 77.5946
      },
      {
        "id": 218,
        "region": "South America",
        "country": "Argentina",
        "city": "Cordoba",
        "sales": 180,
        "product": "Monitor",
        "category": "Electronics",
        "date": "2024-07-04",
        "manager": "Sofia Cruz",
        "latitude": -31.4201,
        "longitude": -64.1888
      },
      {
        "id": 219,
        "region": "North America",
        "country": "Canada",
        "city": "Montreal",
        "sales": 190,
        "product": "Smartwatch",
        "category": "Accessories",
        "date": "2024-08-23",
        "manager": "Marc Lefevre",
        "latitude": 45.5017,
        "longitude": -73.5673
      },
      {
        "id": 220,
        "region": "Europe",
        "country": "Germany",
        "city": "Hamburg",
        "sales": 280,
        "product": "Headphones",
        "category": "Accessories",
        "date": "2024-09-10",
        "manager": "Stefan Becker",
        "latitude": 53.5511,
        "longitude": 9.9937
      }
    ]

  